In [1]:
import pandas as pd
from nba_api.stats.static import teams
from nba_api.stats.static import players
from nba_api.stats.endpoints import leaguegamefinder

import time
start_time = time.time()

In [2]:
path = 'C:/Users/mitchtrainotti/Documents/NBA Project/Data/'
gameRecordName = '01gameRecord.xlsx'

gameRecordNameXls = '01gameRecord.xlsx'

In [3]:
nba_teams = teams.get_teams()
# Select the dictionary for the Celtics, which contains their team ID
warriors = [team for team in nba_teams if team['abbreviation'] == 'GSW'][0]
warriors_id = warriors['id']

In [4]:
nba_players = players.get_players()

warriors_players = []
steph = [player for player in nba_players if player['full_name'] == 'Stephen Curry']

warriors_players.append(steph)

warriors_players

[[{'id': 201939,
   'full_name': 'Stephen Curry',
   'first_name': 'Stephen',
   'last_name': 'Curry',
   'is_active': True}]]

In [5]:
# Query for games where the Warriors were playing
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=warriors_id)
# The first DataFrame of those returned is what we want.
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42021,1610612744,GSW,Golden State Warriors,0042100235,2022-05-11,GSW @ MEM,L,240,95,...,0.692,4.0,33.0,37.0,22,3,5,22,23,-39.0
1,42021,1610612744,GSW,Golden State Warriors,0042100234,2022-05-09,GSW vs. MEM,W,239,101,...,0.909,10.0,44.0,54.0,25,6,7,16,15,3.0
2,42021,1610612744,GSW,Golden State Warriors,0042100233,2022-05-07,GSW vs. MEM,W,241,142,...,0.905,4.0,34.0,38.0,34,5,4,16,24,30.0
3,42021,1610612744,GSW,Golden State Warriors,0042100232,2022-05-03,GSW @ MEM,L,239,101,...,0.778,14.0,38.0,52.0,27,6,2,18,20,-5.0
4,42021,1610612744,GSW,Golden State Warriors,0042100231,2022-05-01,GSW @ MEM,W,239,117,...,0.650,16.0,36.0,52.0,31,10,6,18,25,1.0

In [6]:
games_2122 = games[games.SEASON_ID.str[-5:] == '22021']
games_2122 = games_2122[games_2122.GAME_ID.str[:4] == '0022']
games_2122['homeFlag'] = games_2122['MATCHUP'].str.contains('vs.')


games_2122.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,homeFlag
10,22021,1610612744,GSW,Golden State Warriors,0022101225,2022-04-10,GSW @ NOP,W,240,128,...,7.0,34.0,41.0,33,5,2,17,15,21.0,False
11,22021,1610612744,GSW,Golden State Warriors,0022101215,2022-04-09,GSW @ SAS,W,239,100,...,13.0,38.0,51.0,23,8,1,12,22,6.0,False
12,22021,1610612744,GSW,Golden State Warriors,0022101202,2022-04-07,GSW vs. LAL,W,239,128,...,9.0,36.0,45.0,39,10,5,15,26,16.0,True
13,22021,1610612744,GSW,Golden State Warriors,0022101176,2022-04-03,GSW @ SAC,W,239,109,...,7.0,40.0,47.0,29,8,8,15,28,19.0,False
14,22021,1610612744,GSW,Golden State Warriors,0022101165,2022-04-02,GSW vs. UTA,W,241,111,...,6.0,35.0,41.0,30,5,6,11,22,4.0,True

In [7]:
newPath = path + gameRecordName
writer = pd.ExcelWriter(newPath, engine = 'xlsxwriter')
games_2122.to_excel(writer, gameRecordName)
writer.save()

In [8]:
newPath = path + gameRecordNameXls
writer = pd.ExcelWriter(newPath, engine = 'xlsxwriter')
games_2122.to_excel(writer, 'Sheet1')
writer.save()

print("--- %s seconds ---" % (time.time() - start_time))

--- 1.0673344135284424 seconds ---